import Header from "@/components/Header"
import "../../styles/globals.css"
import Banner from "@/components/Banner"

export const metadata = {
  title: 'The Blog',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="p-10 sm:p-0 sm:max-w-6xl mx-auto">
        <Header/>
        <Banner/>
        {children}
      </body>
    </html>
  )
}
